package yql.msg.common.model.auto.tmsg;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_msg
 *
 * @mbg.generated do_not_delete_during_merge 2017-11-29 18:17:14
 */
public class TMsg implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.id
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private String id;

    /**
     * Database Column Remarks:
     *   消息名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.msg_name
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private String msgName;

    /**
     * Database Column Remarks:
     *   可以发送的总次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.send_num
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private Short sendNum;

    /**
     * Database Column Remarks:
     *   已重试的次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.reset_num
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private Short resetNum;

    /**
     * Database Column Remarks:
     *   重发频率，分钟为单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.reset_rate
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private Integer resetRate;

    /**
     * Database Column Remarks:
     *   上一次发送的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.last_send_time
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private Date lastSendTime;

    /**
     * Database Column Remarks:
     *   状态
     *   。1：待确认，
     *   2：待发送
     *   ，3：发送成功，4：发送失败，
     *   5：处理成功，6：处理失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.status
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private Short status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.create_time
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   消息内容,json格式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_msg.msg_content
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.id
     *
     * @return the value of t_msg.id
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.id
     *
     * @param id the value for t_msg.id
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.msg_name
     *
     * @return the value of t_msg.msg_name
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public String getMsgName() {
        return msgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.msg_name
     *
     * @param msgName the value for t_msg.msg_name
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setMsgName(String msgName) {
        this.msgName = msgName == null ? null : msgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.send_num
     *
     * @return the value of t_msg.send_num
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Short getSendNum() {
        return sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.send_num
     *
     * @param sendNum the value for t_msg.send_num
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setSendNum(Short sendNum) {
        this.sendNum = sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.reset_num
     *
     * @return the value of t_msg.reset_num
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Short getResetNum() {
        return resetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.reset_num
     *
     * @param resetNum the value for t_msg.reset_num
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setResetNum(Short resetNum) {
        this.resetNum = resetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.reset_rate
     *
     * @return the value of t_msg.reset_rate
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Integer getResetRate() {
        return resetRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.reset_rate
     *
     * @param resetRate the value for t_msg.reset_rate
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setResetRate(Integer resetRate) {
        this.resetRate = resetRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.last_send_time
     *
     * @return the value of t_msg.last_send_time
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Date getLastSendTime() {
        return lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.last_send_time
     *
     * @param lastSendTime the value for t_msg.last_send_time
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setLastSendTime(Date lastSendTime) {
        this.lastSendTime = lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.status
     *
     * @return the value of t_msg.status
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.status
     *
     * @param status the value for t_msg.status
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.create_time
     *
     * @return the value of t_msg.create_time
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.create_time
     *
     * @param createTime the value for t_msg.create_time
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_msg.msg_content
     *
     * @return the value of t_msg.msg_content
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_msg.msg_content
     *
     * @param msgContent the value for t_msg.msg_content
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }
}