package yql.msg.common.model.auto.tmsg;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import yql.msg.common.util.mybatis.Page;

public class TMsgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public TMsgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("t.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("t.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("t.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("t.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("t.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("t.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("t.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("t.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("t.id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("t.id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("t.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("t.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("t.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("t.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMsgNameIsNull() {
            addCriterion("t.msg_name is null");
            return (Criteria) this;
        }

        public Criteria andMsgNameIsNotNull() {
            addCriterion("t.msg_name is not null");
            return (Criteria) this;
        }

        public Criteria andMsgNameEqualTo(String value) {
            addCriterion("t.msg_name =", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameNotEqualTo(String value) {
            addCriterion("t.msg_name <>", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameGreaterThan(String value) {
            addCriterion("t.msg_name >", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameGreaterThanOrEqualTo(String value) {
            addCriterion("t.msg_name >=", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameLessThan(String value) {
            addCriterion("t.msg_name <", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameLessThanOrEqualTo(String value) {
            addCriterion("t.msg_name <=", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameLike(String value) {
            addCriterion("t.msg_name like", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameNotLike(String value) {
            addCriterion("t.msg_name not like", value, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameIn(List<String> values) {
            addCriterion("t.msg_name in", values, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameNotIn(List<String> values) {
            addCriterion("t.msg_name not in", values, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameBetween(String value1, String value2) {
            addCriterion("t.msg_name between", value1, value2, "msgName");
            return (Criteria) this;
        }

        public Criteria andMsgNameNotBetween(String value1, String value2) {
            addCriterion("t.msg_name not between", value1, value2, "msgName");
            return (Criteria) this;
        }

        public Criteria andSendNumIsNull() {
            addCriterion("t.send_num is null");
            return (Criteria) this;
        }

        public Criteria andSendNumIsNotNull() {
            addCriterion("t.send_num is not null");
            return (Criteria) this;
        }

        public Criteria andSendNumEqualTo(Short value) {
            addCriterion("t.send_num =", value, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumNotEqualTo(Short value) {
            addCriterion("t.send_num <>", value, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumGreaterThan(Short value) {
            addCriterion("t.send_num >", value, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumGreaterThanOrEqualTo(Short value) {
            addCriterion("t.send_num >=", value, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumLessThan(Short value) {
            addCriterion("t.send_num <", value, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumLessThanOrEqualTo(Short value) {
            addCriterion("t.send_num <=", value, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumIn(List<Short> values) {
            addCriterion("t.send_num in", values, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumNotIn(List<Short> values) {
            addCriterion("t.send_num not in", values, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumBetween(Short value1, Short value2) {
            addCriterion("t.send_num between", value1, value2, "sendNum");
            return (Criteria) this;
        }

        public Criteria andSendNumNotBetween(Short value1, Short value2) {
            addCriterion("t.send_num not between", value1, value2, "sendNum");
            return (Criteria) this;
        }

        public Criteria andResetNumIsNull() {
            addCriterion("t.reset_num is null");
            return (Criteria) this;
        }

        public Criteria andResetNumIsNotNull() {
            addCriterion("t.reset_num is not null");
            return (Criteria) this;
        }

        public Criteria andResetNumEqualTo(Short value) {
            addCriterion("t.reset_num =", value, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumNotEqualTo(Short value) {
            addCriterion("t.reset_num <>", value, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumGreaterThan(Short value) {
            addCriterion("t.reset_num >", value, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumGreaterThanOrEqualTo(Short value) {
            addCriterion("t.reset_num >=", value, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumLessThan(Short value) {
            addCriterion("t.reset_num <", value, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumLessThanOrEqualTo(Short value) {
            addCriterion("t.reset_num <=", value, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumIn(List<Short> values) {
            addCriterion("t.reset_num in", values, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumNotIn(List<Short> values) {
            addCriterion("t.reset_num not in", values, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumBetween(Short value1, Short value2) {
            addCriterion("t.reset_num between", value1, value2, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetNumNotBetween(Short value1, Short value2) {
            addCriterion("t.reset_num not between", value1, value2, "resetNum");
            return (Criteria) this;
        }

        public Criteria andResetRateIsNull() {
            addCriterion("t.reset_rate is null");
            return (Criteria) this;
        }

        public Criteria andResetRateIsNotNull() {
            addCriterion("t.reset_rate is not null");
            return (Criteria) this;
        }

        public Criteria andResetRateEqualTo(Integer value) {
            addCriterion("t.reset_rate =", value, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateNotEqualTo(Integer value) {
            addCriterion("t.reset_rate <>", value, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateGreaterThan(Integer value) {
            addCriterion("t.reset_rate >", value, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("t.reset_rate >=", value, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateLessThan(Integer value) {
            addCriterion("t.reset_rate <", value, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateLessThanOrEqualTo(Integer value) {
            addCriterion("t.reset_rate <=", value, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateIn(List<Integer> values) {
            addCriterion("t.reset_rate in", values, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateNotIn(List<Integer> values) {
            addCriterion("t.reset_rate not in", values, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateBetween(Integer value1, Integer value2) {
            addCriterion("t.reset_rate between", value1, value2, "resetRate");
            return (Criteria) this;
        }

        public Criteria andResetRateNotBetween(Integer value1, Integer value2) {
            addCriterion("t.reset_rate not between", value1, value2, "resetRate");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeIsNull() {
            addCriterion("t.last_send_time is null");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeIsNotNull() {
            addCriterion("t.last_send_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeEqualTo(Date value) {
            addCriterion("t.last_send_time =", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeNotEqualTo(Date value) {
            addCriterion("t.last_send_time <>", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeGreaterThan(Date value) {
            addCriterion("t.last_send_time >", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("t.last_send_time >=", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeLessThan(Date value) {
            addCriterion("t.last_send_time <", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("t.last_send_time <=", value, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeIn(List<Date> values) {
            addCriterion("t.last_send_time in", values, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeNotIn(List<Date> values) {
            addCriterion("t.last_send_time not in", values, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeBetween(Date value1, Date value2) {
            addCriterion("t.last_send_time between", value1, value2, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andLastSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("t.last_send_time not between", value1, value2, "lastSendTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("t.status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("t.status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("t.status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("t.status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("t.status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("t.status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("t.status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("t.status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("t.status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("t.status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("t.status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("t.status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("t.create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("t.create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("t.create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("t.create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("t.create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("t.create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("t.create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("t.create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("t.create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("t.create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("t.create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("t.create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(t.id) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andMsgNameLikeInsensitive(String value) {
            addCriterion("upper(t.msg_name) like", value.toUpperCase(), "msgName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_msg
     *
     * @mbg.generated do_not_delete_during_merge 2017-11-29 18:17:14
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}