package com.mine.dubbo.example.biz.dao.autocode;

import com.mine.dubbo.example.common.model.autocode.TUserAccountDetail;
import com.mine.dubbo.example.common.model.autocode.TUserAccountDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserAccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int countByExample(TUserAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int deleteByExample(TUserAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int deleteByPrimaryKey(String accountDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int insert(TUserAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int insertSelective(TUserAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    List<TUserAccountDetail> selectByExample(TUserAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    TUserAccountDetail selectByPrimaryKey(String accountDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") TUserAccountDetail record, @Param("example") TUserAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int updateByExample(@Param("record") TUserAccountDetail record, @Param("example") TUserAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int updateByPrimaryKeySelective(TUserAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account_detail
     *
     * @mbggenerated Tue Jan 10 15:42:50 CST 2017
     */
    int updateByPrimaryKey(TUserAccountDetail record);
}