package com.mine.dubbo.example.biz.dao.autocode;

import com.mine.dubbo.example.common.model.autocode.TUserAddress;
import com.mine.dubbo.example.common.model.autocode.TUserAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int countByExample(TUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int deleteByExample(TUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int deleteByPrimaryKey(String addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int insert(TUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int insertSelective(TUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    List<TUserAddress> selectByExample(TUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    TUserAddress selectByPrimaryKey(String addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TUserAddress record, @Param("example") TUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int updateByExample(@Param("record") TUserAddress record, @Param("example") TUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int updateByPrimaryKeySelective(TUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_address
     *
     * @mbggenerated Tue Jan 10 15:43:54 CST 2017
     */
    int updateByPrimaryKey(TUserAddress record);
}