package com.mine.study.common.model.autocode;

import java.io.Serializable;
import java.util.Date;

public class TUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_level_id
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Integer userLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_pwd
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mmh
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String mmh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nick_name
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_photo
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String userPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.regist_channel
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Integer registChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_consume_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Date lastConsumeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.creater
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_update_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_update_creater
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String lastUpdateCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.freeze_reason
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private String freezeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_level_id
     *
     * @return the value of t_user.user_level_id
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Integer getUserLevelId() {
        return userLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_level_id
     *
     * @param userLevelId the value for t_user.user_level_id
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setUserLevelId(Integer userLevelId) {
        this.userLevelId = userLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_pwd
     *
     * @return the value of t_user.user_pwd
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_pwd
     *
     * @param userPwd the value for t_user.user_pwd
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mmh
     *
     * @return the value of t_user.mmh
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getMmh() {
        return mmh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mmh
     *
     * @param mmh the value for t_user.mmh
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setMmh(String mmh) {
        this.mmh = mmh == null ? null : mmh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nick_name
     *
     * @return the value of t_user.nick_name
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nick_name
     *
     * @param nickName the value for t_user.nick_name
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_photo
     *
     * @return the value of t_user.user_photo
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getUserPhoto() {
        return userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_photo
     *
     * @param userPhoto the value for t_user.user_photo
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto == null ? null : userPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.regist_channel
     *
     * @return the value of t_user.regist_channel
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Integer getRegistChannel() {
        return registChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.regist_channel
     *
     * @param registChannel the value for t_user.regist_channel
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setRegistChannel(Integer registChannel) {
        this.registChannel = registChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_consume_time
     *
     * @return the value of t_user.last_consume_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Date getLastConsumeTime() {
        return lastConsumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_consume_time
     *
     * @param lastConsumeTime the value for t_user.last_consume_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setLastConsumeTime(Date lastConsumeTime) {
        this.lastConsumeTime = lastConsumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.creater
     *
     * @return the value of t_user.creater
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.creater
     *
     * @param creater the value for t_user.creater
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_update_time
     *
     * @return the value of t_user.last_update_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_update_time
     *
     * @param lastUpdateTime the value for t_user.last_update_time
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_update_creater
     *
     * @return the value of t_user.last_update_creater
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getLastUpdateCreater() {
        return lastUpdateCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_update_creater
     *
     * @param lastUpdateCreater the value for t_user.last_update_creater
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setLastUpdateCreater(String lastUpdateCreater) {
        this.lastUpdateCreater = lastUpdateCreater == null ? null : lastUpdateCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.freeze_reason
     *
     * @return the value of t_user.freeze_reason
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public String getFreezeReason() {
        return freezeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.freeze_reason
     *
     * @param freezeReason the value for t_user.freeze_reason
     *
     * @mbggenerated Sun Nov 13 11:47:08 CST 2016
     */
    public void setFreezeReason(String freezeReason) {
        this.freezeReason = freezeReason == null ? null : freezeReason.trim();
    }
}