package yql.msg.biz.dao.auto.tmsg;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yql.msg.common.model.auto.tmsg.TMsg;
import yql.msg.common.model.auto.tmsg.TMsgExample;

public interface TMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    long countByExample(TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int deleteByExample(TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int insert(TMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int insertSelective(TMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    List<TMsg> selectByExampleWithBLOBs(TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    List<TMsg> selectByExample(TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    TMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int updateByExampleSelective(@Param("record") TMsg record, @Param("example") TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int updateByExampleWithBLOBs(@Param("record") TMsg record, @Param("example") TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int updateByExample(@Param("record") TMsg record, @Param("example") TMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int updateByPrimaryKeySelective(TMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int updateByPrimaryKeyWithBLOBs(TMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated 2017-11-29 18:17:14
     */
    int updateByPrimaryKey(TMsg record);
}