server:
  port: 8080
  
spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.127.129:3306/mock?characterEncoding=UTF-8
    username : root
    password : root