package com.mine.study.api.dao.autocode;

import com.mine.study.common.model.autocode.TUserAccount;
import com.mine.study.common.model.autocode.TUserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int countByExample(TUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int deleteByExample(TUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int insert(TUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int insertSelective(TUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    List<TUserAccount> selectByExample(TUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    TUserAccount selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") TUserAccount record, @Param("example") TUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int updateByExample(@Param("record") TUserAccount record, @Param("example") TUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int updateByPrimaryKeySelective(TUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_account
     *
     * @mbggenerated Mon Dec 19 15:41:08 CST 2016
     */
    int updateByPrimaryKey(TUserAccount record);
}